[2017-11-12 11:11:52] DEBUG [mediconnect.index:13] Entering index method
[2017-11-12 20:45:43] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1971
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /static/js/jquery.twbsPagination.js HTTP/1.1" 200 11819
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37051
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /static/js/jquery.js HTTP/1.1" 200 86711
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121205
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /static/js/vue.js HTTP/1.1" 200 279117
[2017-11-12 20:45:44] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /static/js/jquery-ui.js HTTP/1.1" 200 539419
[2017-11-12 20:45:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-12 20:45:45] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:45:45] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-12 20:45:45] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-12 20:45:46] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3502
[2017-11-12 20:45:46] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:45:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-12 20:45:46] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:46:14] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3502
[2017-11-12 20:46:14] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:46:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-12 20:46:14] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:46:16] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9603
[2017-11-12 20:46:16] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:46:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-12 20:46:16] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-12 20:46:17] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1672
[2017-11-12 20:46:17] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1672
[2017-11-13 09:01:37] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9603
[2017-11-13 09:01:37] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:01:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:01:38] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:01:38] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1672
[2017-11-13 09:01:38] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1672
[2017-11-13 09:01:39] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3503
[2017-11-13 09:01:39] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:01:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:01:39] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:01:43] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/send_reset_link/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 423, in send_reset_link
    user = User.objects.get(id = trans_id)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
[2017-11-13 09:01:43] ERROR [django.server.log_message:124] "GET /supervisor/ajax/send_reset_link/?trans_id=42&password=1234567 HTTP/1.1" 500 17933
[2017-11-13 09:04:07] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3503
[2017-11-13 09:04:07] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:04:07] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:04:07] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:04:16] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/send_reset_link/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 468, in send_reset_link
    email_message.send()
  File "C:\Python27\lib\site-packages\django\core\mail\message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Python27\lib\site-packages\django\core\mail\backends\smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "C:\Python27\lib\site-packages\django\core\mail\backends\smtp.py", line 71, in open
    self.connection.login(force_str(self.username), force_str(self.password))
  File "C:\Python27\lib\smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (451, '4.7.0 Temporary server error. Please try again later. PRX4  [MWHPR22CA0071.namprd22.prod.outlook.com]')
[2017-11-13 09:04:16] ERROR [django.server.log_message:124] "GET /supervisor/ajax/send_reset_link/?trans_id=42&password=1234567 HTTP/1.1" 500 18372
[2017-11-13 09:06:42] INFO [django.server.log_message:124] "GET /supervisor/customer_list/13/ HTTP/1.1" 200 4460
[2017-11-13 09:06:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:06:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:06:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:06:43] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3503
[2017-11-13 09:06:44] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:06:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:06:44] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:06:46] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9603
[2017-11-13 09:06:46] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:06:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:06:46] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:06:46] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1672
[2017-11-13 09:06:46] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1672
[2017-11-13 09:49:44] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1971
[2017-11-13 09:49:44] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:49:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:49:45] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:49:48] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9603
[2017-11-13 09:49:48] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:49:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 09:49:48] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 09:49:48] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1638
[2017-11-13 09:49:48] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1638
[2017-11-13 09:52:08] INFO [django.server.log_message:124] "GET /supervisor/export_csv/ HTTP/1.1" 200 37
[2017-11-13 20:18:02] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1971
[2017-11-13 20:18:03] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 20:18:03] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 20:18:03] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 20:18:04] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-13 20:18:04] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-13 20:18:04] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4105
[2017-11-13 20:18:05] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 20:18:05] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-13 20:18:05] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-13 20:18:06] INFO [django.server.log_message:124] "GET /supervisor/ajax/send_reset_link/?trans_id=42&password= HTTP/1.1" 200 66
[2017-11-17 08:53:29] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1971
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /static/js/jquery.js HTTP/1.1" 200 86711
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121205
[2017-11-17 08:53:30] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /static/js/jquery.twbsPagination.js HTTP/1.1" 200 11819
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37051
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /static/js/vue.js HTTP/1.1" 200 279117
[2017-11-17 08:53:30] INFO [django.server.log_message:124] "GET /static/js/jquery-ui.js HTTP/1.1" 200 539419
[2017-11-17 08:53:30] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:53:31] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-17 08:53:31] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-17 08:53:34] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9605
[2017-11-17 08:53:35] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:53:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:53:35] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:53:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1673
[2017-11-17 08:53:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1673
[2017-11-17 08:54:32] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4056
[2017-11-17 08:54:32] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:54:32] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:54:32] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:54:38] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 08:54:39] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4056
[2017-11-17 08:54:39] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:54:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:54:41] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 08:54:42] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4056
[2017-11-17 08:54:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:54:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:54:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:40] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3951
[2017-11-17 08:57:40] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:57:40] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:48] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 542194
[2017-11-17 08:57:52] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3951
[2017-11-17 08:57:52] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:52] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:57:55] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3951
[2017-11-17 08:57:55] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:55] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:57:56] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:56] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3951
[2017-11-17 08:57:56] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:57:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:57:57] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:58:58] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3958
[2017-11-17 08:58:58] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 08:58:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 08:58:58] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:00:12] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3960
[2017-11-17 09:00:13] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:00:13] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:00:13] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:10:32] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4257
[2017-11-17 09:10:32] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:10:32] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:10:32] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:10:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 09:10:38] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4257
[2017-11-17 09:10:38] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:10:38] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:10:38] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:10:41] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 09:10:42] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4257
[2017-11-17 09:10:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:10:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:10:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:05] INFO [django.server.log_message:124] "GET /supervisor/ajax/send_reset_link/?trans_id=42&password= HTTP/1.1" 200 66
[2017-11-17 09:11:08] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 09:11:09] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4122
[2017-11-17 09:11:09] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:09] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:11:09] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:37] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4104
[2017-11-17 09:11:37] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:11:38] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:38] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 09:11:40] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4104
[2017-11-17 09:11:40] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:11:40] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:59] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4108
[2017-11-17 09:11:59] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:11:59] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:11:59] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:12:30] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4136
[2017-11-17 09:12:30] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:12:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:12:30] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:13:05] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4164
[2017-11-17 09:13:05] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:13:05] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:13:05] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:13:25] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4166
[2017-11-17 09:13:25] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:13:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:13:25] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:13:27] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=42 HTTP/1.1" 200 66
[2017-11-17 09:13:29] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4166
[2017-11-17 09:13:29] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:13:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:13:29] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:15:36] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9605
[2017-11-17 09:15:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:15:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:15:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:15:37] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1673
[2017-11-17 09:15:37] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1673
[2017-11-17 09:18:51] INFO [django.server.log_message:124] "GET /supervisor/export_csv/ HTTP/1.1" 200 37
[2017-11-17 09:19:35] DEBUG [mediconnect.log:16] CSV exported
[2017-11-17 09:19:35] INFO [django.server.log_message:124] "GET /supervisor/export_csv/ HTTP/1.1" 200 37
[2017-11-17 09:51:33] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4109
[2017-11-17 09:51:33] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:51:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:51:33] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:51:41] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 70, in validate_pwd
    auto_assign(each)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 18, in auto_assign
    assignee = Staff.objects.filter(role=1).order_by('sequence')[0]
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[2017-11-17 09:51:41] ERROR [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=42 HTTP/1.1" 500 17943
[2017-11-17 09:51:53] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3774
[2017-11-17 09:51:53] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:51:53] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:51:53] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:51:55] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9605
[2017-11-17 09:51:55] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:51:55] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-17 09:51:56] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-17 09:51:56] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 183, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 178, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-17 09:51:56] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-21 15:34:49] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1971
[2017-11-21 15:34:51] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121205
[2017-11-21 15:34:51] INFO [django.server.log_message:124] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37051
[2017-11-21 15:34:51] INFO [django.server.log_message:124] "GET /static/js/jquery.twbsPagination.js HTTP/1.1" 200 11819
[2017-11-21 15:34:52] INFO [django.server.log_message:124] "GET /static/js/jquery.js HTTP/1.1" 200 86711
[2017-11-21 15:34:52] INFO [django.server.log_message:124] "GET /static/js/vue.js HTTP/1.1" 200 279117
[2017-11-21 15:34:52] INFO [django.server.log_message:124] "GET /static/js/jquery-ui.js HTTP/1.1" 200 539419
[2017-11-21 15:34:52] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-21 15:34:52] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-21 15:34:52] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-21 15:34:53] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-21 15:34:53] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-21 15:34:55] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9605
[2017-11-21 15:34:55] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-21 15:34:55] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-21 15:34:55] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-21 15:34:56] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 183, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 178, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-21 15:34:57] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-21 15:35:00] DEBUG [mediconnect.log:16] CSV exported
[2017-11-21 15:35:00] INFO [django.server.log_message:124] "GET /supervisor/export_csv/ HTTP/1.1" 200 37
[2017-11-22 08:07:23] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1971
[2017-11-22 08:07:23] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:07:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:07:23] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:07:24] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-22 08:07:24] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-22 08:10:28] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9605
[2017-11-22 08:10:28] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:28] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:10:28] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:29] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1662
[2017-11-22 08:10:29] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1662
[2017-11-22 08:10:30] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 3774
[2017-11-22 08:10:30] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:10:30] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:31] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3860
[2017-11-22 08:10:31] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:10:31] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:53] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4109
[2017-11-22 08:10:53] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:10:53] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:10:53] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:34] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=34 HTTP/1.1" 200 66
[2017-11-22 08:11:36] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 3999
[2017-11-22 08:11:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:11:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:42] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4109
[2017-11-22 08:11:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:11:42] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:44] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=34 HTTP/1.1" 200 66
[2017-11-22 08:11:45] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4109
[2017-11-22 08:11:45] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:45] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:11:45] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:13:27] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4189
[2017-11-22 08:13:27] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:13:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:13:27] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:13:29] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 542194
[2017-11-22 08:13:41] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4187
[2017-11-22 08:13:41] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:13:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:14:40] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4220
[2017-11-22 08:14:40] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:14:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:14:40] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:15:41] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4192
[2017-11-22 08:15:41] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:15:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:15:41] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:15:45] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=34 HTTP/1.1" 200 66
[2017-11-22 08:15:46] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4192
[2017-11-22 08:15:46] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:15:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:15:46] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:16:22] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=34 HTTP/1.1" 200 66
[2017-11-22 08:16:25] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4226
[2017-11-22 08:16:25] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:16:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:16:26] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:16:28] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=34 HTTP/1.1" 200 66
[2017-11-22 08:16:29] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4226
[2017-11-22 08:16:29] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:16:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:16:29] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:16:34] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=&trans_id=34 HTTP/1.1" 200 66
[2017-11-22 08:16:36] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4224
[2017-11-22 08:16:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:16:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:16:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:18:36] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4649
[2017-11-22 08:18:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:18:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-22 08:18:36] WARNING [django.server.log_message:124] "GET /static/js/table2CSV.js HTTP/1.1" 404 1772
[2017-11-22 08:19:10] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-22 08:19:10] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:02:37] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-25 09:02:38] INFO [django.server.log_message:124] "GET /static/js/jquery.twbsPagination.js HTTP/1.1" 200 11819
[2017-11-25 09:02:39] INFO [django.server.log_message:124] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37051
[2017-11-25 09:02:39] INFO [django.server.log_message:124] "GET /static/js/jquery.js HTTP/1.1" 200 86711
[2017-11-25 09:02:39] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121205
[2017-11-25 09:02:39] INFO [django.server.log_message:124] "GET /static/js/vue.js HTTP/1.1" 200 279117
[2017-11-25 09:02:39] INFO [django.server.log_message:124] "GET /static/js/jquery-ui.js HTTP/1.1" 200 539419
[2017-11-25 09:02:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:02:39] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-25 09:02:39] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-25 09:02:41] INFO [django.server.log_message:124] "GET /signup/ HTTP/1.1" 200 6179
[2017-11-25 09:02:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:03:13] INFO [django.server.log_message:124] "GET /signup/ HTTP/1.1" 200 5989
[2017-11-25 09:03:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:03:33] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-11-25 09:03:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:10:33] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-11-25 09:10:33] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1919
[2017-11-25 09:10:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:10:36] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:10:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:10:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1662
[2017-11-25 09:10:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1662
[2017-11-25 09:10:38] INFO [django.server.log_message:124] "GET /supervisor/detail/13/163/ HTTP/1.1" 200 4084
[2017-11-25 09:10:38] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:10:40] INFO [django.server.log_message:124] "GET /supervisor/generate_questionnaire/3/10/ HTTP/1.1" 200 6608
[2017-11-25 09:10:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:11:01] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/create_questionnaire/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 559, in create_questionnaire
    tuple_= ("Question Number: ",each,"Question: ",data[each]["question"],"Question Format: ",data[each]["format"],"Choices: ",)
KeyError: u'format'
[2017-11-25 09:11:02] ERROR [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%221%22%2C%22question%22%3A%22%22%2C%22choices%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%7D%2C%221%22%3A%7B%22format%22%3A%222%22%2C%22question%22%3A%22%22%2C%22choices%22%3A%5B%5D%7D%2C%222%22%3A%7B%22question%22%3A%22%22%2C%22choices%22%3A%5B%5D%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 500 18395
[2017-11-25 09:11:19] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 542194
[2017-11-25 09:13:01] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/create_questionnaire/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 568, in create_questionnaire
    assignee = Staff.objects.filter(role=2).order_by('sequence')[0]
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[2017-11-25 09:13:01] ERROR [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%221%22%2C%22question%22%3A%22%22%2C%22choices%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%7D%2C%221%22%3A%7B%22format%22%3A%222%22%2C%22question%22%3A%22%22%2C%22choices%22%3A%5B%5D%7D%2C%222%22%3A%7B%22question%22%3A%22%22%2C%22choices%22%3A%5B%5D%2C%22format%22%3A%220%22%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 500 18538
[2017-11-25 09:13:06] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/create_questionnaire/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 568, in create_questionnaire
    assignee = Staff.objects.filter(role=2).order_by('sequence')[0]
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[2017-11-25 09:13:06] ERROR [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%221%22%2C%22question%22%3A%22%22%2C%22choices%22%3A%5B%22%22%2C%22%22%2C%22%22%2C%22%22%5D%7D%2C%221%22%3A%7B%22format%22%3A%222%22%2C%22question%22%3A%22%22%2C%22choices%22%3A%5B%5D%7D%2C%222%22%3A%7B%22question%22%3A%22%22%2C%22choices%22%3A%5B%5D%2C%22format%22%3A%220%22%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 500 18538
[2017-11-25 09:14:20] INFO [django.server.log_message:124] "GET /supervisor/generate_questionnaire/3/10/ HTTP/1.1" 200 6718
[2017-11-25 09:14:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:15:35] INFO [django.server.log_message:124] "GET /supervisor/generate_questionnaire/3/10/ HTTP/1.1" 200 6745
[2017-11-25 09:15:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:16:03] INFO [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%220%22%2C%22question%22%3A%22aaa%22%2C%22choices%22%3A%5B%22123%22%2C%22333%22%5D%7D%2C%221%22%3A%7B%22format%22%3A%221%22%2C%22question%22%3A%22bbb%22%2C%22choices%22%3A%5B%22444%22%2C%22555%22%5D%7D%2C%222%22%3A%7B%22format%22%3A%222%22%2C%22question%22%3A%22ccc%22%2C%22choices%22%3A%5B%5D%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 200 5
[2017-11-25 09:23:00] INFO [django.server.log_message:124] "GET /supervisor/generate_questionnaire/3/10/ HTTP/1.1" 200 6745
[2017-11-25 09:23:00] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:23:08] INFO [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%220%22%2C%22question%22%3A%22aaa%22%2C%22choices%22%3A%5B%2222%22%2C%2233%22%5D%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 200 43
[2017-11-25 09:23:29] INFO [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%220%22%2C%22question%22%3A%22aaa%22%2C%22choices%22%3A%5B%2222%22%2C%2233%22%5D%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 200 43
[2017-11-25 09:23:32] INFO [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%220%22%2C%22question%22%3A%22aaa%22%2C%22choices%22%3A%5B%2222%22%2C%2233%22%5D%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 200 43
[2017-11-25 09:23:33] INFO [django.server.log_message:124] "GET /supervisor/ajax/create_questionnaire/?data=%7B%220%22%3A%7B%22format%22%3A%220%22%2C%22question%22%3A%22aaa%22%2C%22choices%22%3A%5B%2222%22%2C%2233%22%5D%7D%7D&hospital=3&disease=10&category=unknown HTTP/1.1" 200 43
[2017-11-25 09:28:01] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:28:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:28:07] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=34 HTTP/1.1" 200 53
[2017-11-25 09:28:08] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:28:08] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:28:30] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:28:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:28:31] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1662
[2017-11-25 09:28:31] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1662
[2017-11-25 09:29:07] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:29:07] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:29:09] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-25 09:29:09] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:29:33] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-25 09:29:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:29:56] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=35 HTTP/1.1" 200 53
[2017-11-25 09:29:58] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-25 09:29:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:30:03] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 3947
[2017-11-25 09:30:03] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:30:05] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:30:05] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:30:26] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=36 HTTP/1.1" 200 53
[2017-11-25 09:30:28] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:30:28] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:40:06] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-25 09:40:06] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:40:27] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-25 09:40:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:40:28] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:40:28] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:40:56] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 70, in validate_pwd
    auto_assign(each)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 18, in auto_assign
    assignee = Staff.objects.filter(role=1).order_by('sequence')[0]
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[2017-11-25 09:40:56] ERROR [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=37 HTTP/1.1" 500 17943
[2017-11-25 09:41:00] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 64, in validate_pwd
    translator = Staff.objects.get(user_id = id)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-25 09:41:00] ERROR [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=37 HTTP/1.1" 500 17996
[2017-11-25 09:41:01] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:41:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:41:04] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:41:04] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:41:04] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1662
[2017-11-25 09:41:04] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1662
[2017-11-25 09:47:26] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:47:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:47:26] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1627
[2017-11-25 09:47:26] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1627
[2017-11-25 09:47:27] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:47:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:47:28] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-25 09:47:28] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:47:46] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-25 09:47:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:47:48] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:47:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:47:50] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:47:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:47:50] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1627
[2017-11-25 09:47:50] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1627
[2017-11-25 09:47:51] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:47:51] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:48:13] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:48:13] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:48:13] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1640
[2017-11-25 09:48:13] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1640
[2017-11-25 09:48:28] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:48:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:48:29] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1639
[2017-11-25 09:48:29] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1639
[2017-11-25 09:48:33] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:48:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:48:39] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 70, in validate_pwd
    auto_assign(each)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 27, in auto_assign
    assignee.set_sequence(timezone.now())
AttributeError: 'NoneType' object has no attribute 'set_sequence'
[2017-11-25 09:48:39] ERROR [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=38 HTTP/1.1" 500 17864
[2017-11-25 09:48:40] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:48:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:48:44] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:48:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:48:44] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1633
[2017-11-25 09:48:44] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1633
[2017-11-25 09:51:39] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:51:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:51:42] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-25 09:51:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:05] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 3998
[2017-11-25 09:52:05] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:14] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-25 09:52:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:17] INFO [django.server.log_message:124] "GET /supervisor/home/13/ HTTP/1.1" 200 1919
[2017-11-25 09:52:17] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:19] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:52:19] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:19] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1633
[2017-11-25 09:52:20] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1633
[2017-11-25 09:52:35] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:52:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1645
[2017-11-25 09:52:36] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1645
[2017-11-25 09:52:38] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:52:38] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:43] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=39 HTTP/1.1" 200 53
[2017-11-25 09:52:44] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:52:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:46] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:52:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:52:46] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1633
[2017-11-25 09:52:47] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1633
[2017-11-25 09:54:19] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:54:19] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:54:21] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-25 09:54:21] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:54:43] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-25 09:54:43] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:54:45] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:54:45] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:55:00] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:55:00] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:55:01] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 191, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 190, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-25 09:55:01] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-25 09:55:22] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:55:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:55:22] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1645
[2017-11-25 09:55:22] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1645
[2017-11-25 09:55:26] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-25 09:55:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:55:30] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=40 HTTP/1.1" 200 53
[2017-11-25 09:55:31] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:55:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:55:33] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-25 09:55:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:55:33] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 191, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 190, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-25 09:55:33] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-25 09:56:48] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-25 09:56:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-25 09:56:50] INFO [django.server.log_message:124] "GET /supervisor/home/13/ HTTP/1.1" 200 1919
[2017-11-25 09:56:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:40:41] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1919
[2017-11-26 08:40:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:40:45] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-26 08:40:45] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:40:46] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 191, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 190, in get_translator_C2E
    print self.translator_C2E
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-26 08:40:46] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18316
[2017-11-26 08:41:25] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-26 08:41:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:41:26] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:41:26] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:41:40] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9553
[2017-11-26 08:41:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:41:41] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:41:41] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:42:36] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:42:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:42:37] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:42:37] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:46:35] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 08:46:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:46:37] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-26 08:46:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:46:55] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 3998
[2017-11-26 08:46:55] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:47:05] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/trans_signup/13/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 266, in trans_signup
    'supervisor': supervisor
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 911, in _resolve_lookup
    current = current()
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 383, in get_assignment_number
    return len(self.get_assignments())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 339, in get_assignments
    for order in Order.objects.filter(Q(translator_C2E=self.id)).order_by('submit'):
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 250, in __iter__
    self._fetch_all()
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 894, in execute_sql
    raise original_exception
OperationalError: (1054, "Unknown column 'order.c2e_re_assigned' in 'field list'")
[2017-11-26 08:47:06] ERROR [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 500 236613
[2017-11-26 08:48:13] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 3947
[2017-11-26 08:48:13] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:22] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 3947
[2017-11-26 08:48:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:27] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-26 08:48:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:31] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:48:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:32] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:48:32] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:48:34] INFO [django.server.log_message:124] "GET /supervisor/detail/13/163/ HTTP/1.1" 200 4084
[2017-11-26 08:48:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:37] INFO [django.server.log_message:124] "GET /supervisor/assign/13/163/ HTTP/1.1" 200 2290
[2017-11-26 08:48:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:46] INFO [django.server.log_message:124] "GET /supervisor/home/13/ HTTP/1.1" 200 1919
[2017-11-26 08:48:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:48] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:48:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:48:49] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:48:49] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:49:15] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:49:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:49:15] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1680
[2017-11-26 08:49:15] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1680
[2017-11-26 08:49:18] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4597
[2017-11-26 08:49:18] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:49:24] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 70, in validate_pwd
    print each.get_translator_C2E()
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 191, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-26 08:49:24] ERROR [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=41 HTTP/1.1" 500 18305
[2017-11-26 08:49:44] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 08:49:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:50:32] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 08:50:32] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:50:42] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4587
[2017-11-26 08:50:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:51:10] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=33 HTTP/1.1" 200 53
[2017-11-26 08:51:11] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 08:51:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:51:14] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:51:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:51:14] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 194, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 191, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-26 08:51:15] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-26 08:52:34] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:52:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:52:35] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 194, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 189, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-26 08:52:35] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-26 08:54:10] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:54:10] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:54:11] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:54:11] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:54:11] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:54:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:54:12] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1668
[2017-11-26 08:54:12] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1668
[2017-11-26 08:55:03] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:55:03] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:55:04] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1666
[2017-11-26 08:55:04] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1666
[2017-11-26 08:56:05] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:56:05] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:56:06] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1675
[2017-11-26 08:56:06] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1675
[2017-11-26 08:56:49] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4592
[2017-11-26 08:56:49] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:56:54] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=31 HTTP/1.1" 200 53
[2017-11-26 08:56:56] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 08:56:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:56:58] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9555
[2017-11-26 08:56:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 08:56:59] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1666
[2017-11-26 08:56:59] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1666
[2017-11-26 09:02:22] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:02:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:02:22] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/update_result/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 194, in update_result
    data['result']['Translator_C2E'].append(each.get_translator_C2E())
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 190, in get_translator_C2E
    if self.translator_C2E is None:
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-26 09:02:22] ERROR [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 500 18322
[2017-11-26 09:03:16] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:03:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:03:16] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1671
[2017-11-26 09:03:17] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1671
[2017-11-26 09:03:19] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4594
[2017-11-26 09:03:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:03:48] INFO [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=30 HTTP/1.1" 200 53
[2017-11-26 09:03:49] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 09:03:49] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:03:51] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:03:51] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:03:52] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1666
[2017-11-26 09:03:52] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1666
[2017-11-26 09:04:29] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:04:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:04:30] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1666
[2017-11-26 09:04:30] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1666
[2017-11-26 09:04:44] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 09:04:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:04:54] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:04:54] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:04:55] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1666
[2017-11-26 09:04:55] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1666
[2017-11-26 09:06:18] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:06:18] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:06:19] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1663
[2017-11-26 09:06:19] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1663
[2017-11-26 09:06:20] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4590
[2017-11-26 09:06:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:06:26] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 74, in validate_pwd
    each.c2e_reassigned = True
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 26, in auto_assign
    order.set_translator_C2E(None)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\helper\models.py", line 201, in set_translator_C2E
    self.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Python27\lib\site-packages\MySQLdb\cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mediconnect`.`order`, CONSTRAINT `order_customer_id_9da9253f_fk_auth_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `auth_customer` (`id`))')
[2017-11-26 09:06:41] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/ajax/validate_pwd/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 64, in validate_pwd
    translator = Staff.objects.get(user_id = id)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Staff matching query does not exist.
[2017-11-26 09:06:41] ERROR [django.server.log_message:124] "GET /supervisor/ajax/validate_pwd/?password=1234567&trans_id=32 HTTP/1.1" 500 17996
[2017-11-26 09:06:44] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-26 09:06:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:06:46] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-26 09:06:47] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:06:47] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1173
[2017-11-26 09:06:47] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1173
[2017-11-26 09:10:19] INFO [django.server.log_message:124] "GET /supervisor/logout/ HTTP/1.1" 302 0
[2017-11-26 09:10:19] INFO [django.server.log_message:124] "GET /supervisor/login HTTP/1.1" 301 0
[2017-11-26 09:10:19] INFO [django.server.log_message:124] "GET /supervisor/login/ HTTP/1.1" 200 3855
[2017-11-26 09:10:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:10:22] INFO [django.server.log_message:124] "GET /signup/ HTTP/1.1" 200 5989
[2017-11-26 09:10:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:11:04] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /signup/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\core\views.py", line 84, in signup
    {'form': SignUpForm()})
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python27\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
[2017-11-26 09:11:04] ERROR [django.server.log_message:124] "GET /signup/ HTTP/1.1" 500 196029
[2017-11-26 09:13:37] INFO [django.server.log_message:124] "GET /signup/ HTTP/1.1" 200 6119
[2017-11-26 09:13:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:13:41] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-11-26 09:13:42] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:13:44] INFO [django.server.log_message:124] "GET /core/password_reset/ HTTP/1.1" 200 2956
[2017-11-26 09:13:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:15:10] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-26 09:15:10] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:15:12] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4262
[2017-11-26 09:15:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:15:16] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-26 09:15:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:15:20] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4262
[2017-11-26 09:15:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:15:26] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-26 09:15:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:15:31] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4634
[2017-11-26 09:15:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:17:11] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4696
[2017-11-26 09:17:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:17:57] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4706
[2017-11-26 09:17:57] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:18:05] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4626
[2017-11-26 09:18:05] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:18:11] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4710
[2017-11-26 09:18:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:18:35] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4626
[2017-11-26 09:18:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:18:53] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4629
[2017-11-26 09:18:53] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:18:59] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4634
[2017-11-26 09:18:59] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:19:40] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4699
[2017-11-26 09:19:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:20:23] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4699
[2017-11-26 09:20:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:20:24] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-26 09:20:24] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:20:26] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4393
[2017-11-26 09:20:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:20:40] INFO [django.server.log_message:124] "POST /result_guest/ HTTP/1.1" 200 4320
[2017-11-26 09:20:40] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:22:53] WARNING [django.request.get_response:152] Not Found: /info/review
[2017-11-26 09:22:53] WARNING [django.server.log_message:124] "GET /info/review HTTP/1.1" 404 7192
[2017-11-26 09:22:57] INFO [django.server.log_message:124] "GET /logout/ HTTP/1.1" 302 0
[2017-11-26 09:22:57] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-26 09:22:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:22:59] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-11-26 09:22:59] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:23:27] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-11-26 09:23:28] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-26 09:23:28] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:23:31] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 3541
[2017-11-26 09:23:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:23:33] INFO [django.server.log_message:124] "GET /info/order/finished/ HTTP/1.1" 200 3541
[2017-11-26 09:23:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-26 09:23:34] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 3541
[2017-11-26 09:23:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:02:47] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /static/js/jquery.js HTTP/1.1" 200 86711
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121205
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /static/js/jquery.twbsPagination.js HTTP/1.1" 200 11819
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /static/js/jquery-ui.js HTTP/1.1" 200 539419
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /static/js/vue.js HTTP/1.1" 200 279117
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37051
[2017-11-28 11:02:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:02:49] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-11-28 11:02:49] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-11-28 11:03:09] INFO [django.server.log_message:124] "GET /logout/ HTTP/1.1" 302 0
[2017-11-28 11:03:09] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-28 11:03:09] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:11] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-11-28 11:03:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:18] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-11-28 11:03:19] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1919
[2017-11-28 11:03:19] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:21] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-28 11:03:21] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:22] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1173
[2017-11-28 11:03:22] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1173
[2017-11-28 11:03:25] INFO [django.server.log_message:124] "GET /supervisor/logout/ HTTP/1.1" 302 0
[2017-11-28 11:03:25] INFO [django.server.log_message:124] "GET /supervisor/login HTTP/1.1" 301 0
[2017-11-28 11:03:25] INFO [django.server.log_message:124] "GET /supervisor/login/ HTTP/1.1" 200 3855
[2017-11-28 11:03:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:37] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-11-28 11:03:37] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-28 11:03:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:38] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4331
[2017-11-28 11:03:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:43] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 6104
[2017-11-28 11:03:43] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:03:43] INFO [django.server.log_message:124] "GET /media/hospital_1/lenna.png HTTP/1.1" 200 473831
[2017-11-28 11:03:43] INFO [django.server.log_message:124] "GET /media/hospital_3/lenna.png HTTP/1.1" 200 473831
[2017-11-28 11:03:43] INFO [django.server.log_message:124] "GET /media/hospital_2/lenna.png HTTP/1.1" 200 473831
[2017-11-28 11:03:45] INFO [django.server.log_message:124] "GET /helper/order/basic/10/3/1 HTTP/1.1" 302 0
[2017-11-28 11:03:46] INFO [django.server.log_message:124] "GET /helper/order/basic/1/1 HTTP/1.1" 200 6451
[2017-11-28 11:03:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:00] INFO [django.server.log_message:124] "POST /helper/order/disease/1/ HTTP/1.1" 200 4992
[2017-11-28 11:04:00] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:24] INFO [django.server.log_message:124] "POST /helper/order/document/1/ HTTP/1.1" 200 3442
[2017-11-28 11:04:24] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:27] INFO [django.server.log_message:124] "GET /helper/order/deposit/1/?csrfmiddlewaretoken=gtDAIr61fQ2jQpJU5icMT2BZEOUV82ihEGhGGpSaDCrjeHl0HAzaCE9Fba5lcohP HTTP/1.1" 200 2980
[2017-11-28 11:04:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:30] INFO [django.server.log_message:124] "POST /helper/order/deposit/1/?csrfmiddlewaretoken=gtDAIr61fQ2jQpJU5icMT2BZEOUV82ihEGhGGpSaDCrjeHl0HAzaCE9Fba5lcohP HTTP/1.1" 302 0
[2017-11-28 11:04:30] INFO [django.server.log_message:124] "GET /helper/order/submit/1/ HTTP/1.1" 200 2550
[2017-11-28 11:04:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:33] INFO [django.server.log_message:124] "GET /logout/ HTTP/1.1" 302 0
[2017-11-28 11:04:33] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-11-28 11:04:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:36] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-11-28 11:04:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:41] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-11-28 11:04:41] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 1919
[2017-11-28 11:04:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:43] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-28 11:04:43] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:43] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1622
[2017-11-28 11:04:43] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1622
[2017-11-28 11:04:48] INFO [django.server.log_message:124] "GET /supervisor/translator_list/13/ HTTP/1.1" 200 4261
[2017-11-28 11:04:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:04:50] INFO [django.server.log_message:124] "GET /supervisor/trans_signup/13/ HTTP/1.1" 200 3808
[2017-11-28 11:04:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:05:08] INFO [django.server.log_message:124] "POST /supervisor/trans_signup/13/ HTTP/1.1" 200 4597
[2017-11-28 11:05:08] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:05:12] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-28 11:05:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:05:12] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1622
[2017-11-28 11:05:12] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1622
[2017-11-28 11:05:14] INFO [django.server.log_message:124] "GET /supervisor/detail/13/1/ HTTP/1.1" 200 3326
[2017-11-28 11:05:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:05:16] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2093
[2017-11-28 11:05:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:05:43] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2134
[2017-11-28 11:05:43] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:05:57] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2134
[2017-11-28 11:05:57] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:06:17] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2163
[2017-11-28 11:06:18] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:06:31] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/assign/13/1/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 324, in assign
    'assignee_choices': C2E_assignee_choice
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '[0]' from 'obj[0]'
[2017-11-28 11:06:31] ERROR [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 500 126539
[2017-11-28 11:06:48] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2163
[2017-11-28 11:06:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:25:09] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2107
[2017-11-28 11:25:10] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:25:12] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 542194
[2017-11-28 11:25:14] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2107
[2017-11-28 11:25:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:25:34] INFO [django.server.log_message:124] "GET /supervisor/orders/13/All/ HTTP/1.1" 200 9551
[2017-11-28 11:25:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:25:35] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D HTTP/1.1" 200 1622
[2017-11-28 11:25:35] INFO [django.server.log_message:124] "GET /supervisor/ajax/update_result/?status=All&query=%7B%7D&page=1 HTTP/1.1" 200 1622
[2017-11-28 11:25:36] INFO [django.server.log_message:124] "GET /supervisor/detail/13/1/ HTTP/1.1" 200 3326
[2017-11-28 11:25:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:25:38] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2107
[2017-11-28 11:25:38] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:25:50] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2107
[2017-11-28 11:25:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:26:14] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2107
[2017-11-28 11:26:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:28:04] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2254
[2017-11-28 11:28:04] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:28:24] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2213
[2017-11-28 11:28:24] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:28:31] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2226
[2017-11-28 11:28:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:31:22] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2296
[2017-11-28 11:31:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:35:49] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2476
[2017-11-28 11:35:49] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:36:02] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2355
[2017-11-28 11:36:02] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:37:02] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2355
[2017-11-28 11:37:02] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:40:52] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2355
[2017-11-28 11:40:52] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:45:00] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /supervisor/assign/13/1/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Project\website\medi_connect_site\supervisor\views.py", line 282, in assign
    C2E_assignee_choice.append((e.user.id, e.get_name()))
AttributeError: 'str' object has no attribute 'append'
[2017-11-28 11:45:01] ERROR [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 500 76895
[2017-11-28 11:45:21] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2233
[2017-11-28 11:45:21] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:45:50] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2264
[2017-11-28 11:45:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:46:23] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2295
[2017-11-28 11:46:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:47:12] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2307
[2017-11-28 11:47:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:47:29] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2269
[2017-11-28 11:47:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:50:11] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2269
[2017-11-28 11:50:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:53:23] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2203
[2017-11-28 11:53:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 11:53:47] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2260
[2017-11-28 11:53:47] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:01:39] INFO [django.server.log_message:124] "GET /supervisor/assign/13/1/ HTTP/1.1" 200 2170
[2017-11-28 12:01:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:07:27] INFO [django.server.log_message:124] "GET /supervisor/logout/ HTTP/1.1" 302 0
[2017-11-28 12:07:27] INFO [django.server.log_message:124] "GET /supervisor/login/ HTTP/1.1" 200 3855
[2017-11-28 12:07:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:07:37] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-11-28 12:07:37] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-28 12:07:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:07:41] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 2595
[2017-11-28 12:07:41] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:08:12] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-28 12:08:16] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4331
[2017-11-28 12:08:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:08:21] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4331
[2017-11-28 12:08:21] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:08:27] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 6104
[2017-11-28 12:08:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:10:01] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3001
[2017-11-28 12:10:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:10:16] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4331
[2017-11-28 12:10:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:10:19] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 6483
[2017-11-28 12:10:19] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:10:57] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3001
[2017-11-28 12:10:57] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:11:30] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3062
[2017-11-28 12:11:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:11:44] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3062
[2017-11-28 12:11:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:12:08] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3062
[2017-11-28 12:12:08] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:12:11] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-28 12:12:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:12:14] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4331
[2017-11-28 12:12:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:12:20] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3062
[2017-11-28 12:12:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:13:24] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3062
[2017-11-28 12:13:24] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:13:58] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 3062
[2017-11-28 12:13:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:14:45] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4570
[2017-11-28 12:14:45] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:14:48] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3998
[2017-11-28 12:14:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-11-28 12:14:51] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4570
[2017-11-28 12:14:51] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /static/js/jquery.twbsPagination.js HTTP/1.1" 200 11482
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37045
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121200
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /static/js/jquery.js HTTP/1.1" 200 86708
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /static/js/vue.js HTTP/1.1" 200 268934
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 12:56:22] INFO [django.server.log_message:124] "GET /static/js/jquery-ui.js HTTP/1.1" 200 520714
[2017-12-05 12:56:22] WARNING [django.request.get_response:152] Not Found: /favicon.ico
[2017-12-05 12:56:22] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 4140
[2017-12-05 12:56:30] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-12-05 12:56:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 12:59:02] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 200 3920
[2017-12-05 12:59:02] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 12:59:06] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 200 3920
[2017-12-05 12:59:06] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 12:59:14] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-12-05 12:59:14] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 12:59:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:00:35] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:00:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:00:39] INFO [django.server.log_message:124] "GET /core/disease_choice/9/ HTTP/1.1" 200 4492
[2017-12-05 13:00:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:00:47] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:00:47] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:00:47] INFO [django.server.log_message:124] "GET /media/hospital_1/lenna.png HTTP/1.1" 200 473831
[2017-12-05 13:00:47] INFO [django.server.log_message:124] "GET /media/hospital_2/lenna.png HTTP/1.1" 200 473831
[2017-12-05 13:00:47] INFO [django.server.log_message:124] "GET /media/hospital_3/lenna.png HTTP/1.1" 200 473831
[2017-12-05 13:00:50] INFO [django.server.log_message:124] "GET /helper/order/basic/10/3/1 HTTP/1.1" 302 0
[2017-12-05 13:00:50] INFO [django.server.log_message:124] "GET /helper/order/basic/173/1 HTTP/1.1" 200 6445
[2017-12-05 13:00:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:03:22] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 13:03:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:05:08] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:05:08] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:05:13] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:05:13] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:05:14] INFO [django.server.log_message:124] "GET /helper/order/basic/10/1/1 HTTP/1.1" 302 0
[2017-12-05 13:05:15] INFO [django.server.log_message:124] "GET /helper/order/basic/174/1 HTTP/1.1" 200 6445
[2017-12-05 13:05:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:06:22] INFO [django.server.log_message:124] "GET /helper/order/basic/10/2/1 HTTP/1.1" 302 0
[2017-12-05 13:06:22] INFO [django.server.log_message:124] "GET /helper/order/basic/175/1 HTTP/1.1" 200 6445
[2017-12-05 13:06:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:06:34] INFO [django.server.log_message:124] "GET /helper/hospital/2/10/ HTTP/1.1" 200 6539
[2017-12-05 13:06:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:06:34] INFO [django.server.log_message:124] "GET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[2017-12-05 13:06:34] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=2&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 13:06:37] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /helper/order/basic/175/3
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/helper/views.py", line 171, in order_info_first
    order = Order.objects.get(id=order_id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/query.py", line 379, in get
    self.model._meta.object_name
DoesNotExist: Order matching query does not exist.
[2017-12-05 13:06:37] ERROR [django.server.log_message:124] "POST /helper/order/basic/175/3 HTTP/1.1" 500 82881
[2017-12-05 13:07:05] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /helper/order/basic/175/1
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/helper/views.py", line 171, in order_info_first
    order = Order.objects.get(id=order_id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/query.py", line 379, in get
    self.model._meta.object_name
DoesNotExist: Order matching query does not exist.
[2017-12-05 13:07:05] ERROR [django.server.log_message:124] "POST /helper/order/basic/175/1 HTTP/1.1" 500 82881
[2017-12-05 13:07:13] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:07:14] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 13:07:15] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:07:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:07:18] INFO [django.server.log_message:124] "GET /core/disease_choice/11/ HTTP/1.1" 200 4492
[2017-12-05 13:07:18] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:07:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:07:20] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:07:23] INFO [django.server.log_message:124] "GET /helper/hospital/2/10/ HTTP/1.1" 200 6539
[2017-12-05 13:07:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:07:23] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=2&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 13:07:25] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /helper/order/basic/176/1
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/helper/views.py", line 171, in order_info_first
    order = Order.objects.get(id=order_id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/query.py", line 379, in get
    self.model._meta.object_name
DoesNotExist: Order matching query does not exist.
[2017-12-05 13:07:25] ERROR [django.server.log_message:124] "POST /helper/order/basic/176/1 HTTP/1.1" 500 82881
[2017-12-05 13:07:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:07:44] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 13:08:54] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:08:54] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:08:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:08:57] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:09:00] INFO [django.server.log_message:124] "GET /helper/order/basic/10/3/1 HTTP/1.1" 302 0
[2017-12-05 13:09:00] INFO [django.server.log_message:124] "GET /helper/order/basic/173/1 HTTP/1.1" 200 6445
[2017-12-05 13:09:00] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:18:56] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 13:18:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:18:57] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:18:57] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:19:00] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:19:00] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:19:02] INFO [django.server.log_message:124] "GET /helper/hospital/3/10/ HTTP/1.1" 200 6554
[2017-12-05 13:19:02] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:19:02] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=3&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 13:20:57] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4107
[2017-12-05 13:20:57] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:21:01] INFO [django.server.log_message:124] "GET /info/order/finished/ HTTP/1.1" 200 3537
[2017-12-05 13:21:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:21:03] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4107
[2017-12-05 13:21:03] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:22:03] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:22:03] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 13:24:20] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:24:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:23] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:23] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:24:27] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 3537
[2017-12-05 13:24:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:30] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 3537
[2017-12-05 13:24:32] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:32] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 13:24:35] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 13:24:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 13:24:39] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 13:24:50] INFO [django.server.log_message:124] "GET /helper/order/basic/10/3/1 HTTP/1.1" 302 0
[2017-12-05 13:24:50] INFO [django.server.log_message:124] "GET /helper/order/basic/178/1 HTTP/1.1" 200 6445
[2017-12-05 13:24:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:19:25] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 15:19:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:19:33] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:19:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:20:08] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:20:08] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:20:21] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 7966
[2017-12-05 15:20:21] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:20:25] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:20:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:22:35] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:22:35] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:23:21] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /result/
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/core/views.py", line 103, in result
    keywords = unit.keyword.split('')
ValueError: empty separator
[2017-12-05 15:23:22] ERROR [django.server.log_message:124] "POST /result/ HTTP/1.1" 500 69993
[2017-12-05 15:23:37] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:23:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:23:54] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:23:54] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:25:09] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:25:09] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:25:22] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:25:22] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:25:46] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:25:46] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:26:37] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 7966
[2017-12-05 15:26:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:31:20] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:31:20] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:36:06] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:36:06] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:36:30] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4661
[2017-12-05 15:36:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:36:38] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4667
[2017-12-05 15:36:38] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:37:56] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 5662
[2017-12-05 15:37:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:38:01] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:38:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:38:07] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 5662
[2017-12-05 15:38:07] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:38:18] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 5662
[2017-12-05 15:38:18] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:38:25] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:38:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:39:12] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:39:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:39:15] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:39:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:39:25] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 5662
[2017-12-05 15:39:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:39:36] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:39:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:39:56] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:39:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:40:00] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 5058
[2017-12-05 15:40:00] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:40:07] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:40:07] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:40:15] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4492
[2017-12-05 15:40:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:42:12] INFO [django.server.log_message:124] "GET /logout/ HTTP/1.1" 302 0
[2017-12-05 15:42:12] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3073
[2017-12-05 15:42:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:42:25] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-12-05 15:42:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:42:37] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 200 3920
[2017-12-05 15:42:38] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:42:43] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:42:43] INFO [django.server.log_message:124] "GET /login/ HTTP/1.1" 200 3855
[2017-12-05 15:59:14] INFO [django.server.log_message:124] "POST /login/ HTTP/1.1" 302 0
[2017-12-05 15:59:14] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 15:59:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:16] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:59:16] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:24] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 15:59:24] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:26] INFO [django.server.log_message:124] "GET /helper/hospital/3/10/ HTTP/1.1" 200 6554
[2017-12-05 15:59:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:26] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=3&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 15:59:29] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /helper/order/basic/178/1
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/helper/views.py", line 169, in order_info_first
    order = Order.objects.get(id=order_id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/query.py", line 379, in get
    self.model._meta.object_name
DoesNotExist: Order matching query does not exist.
[2017-12-05 15:59:29] ERROR [django.server.log_message:124] "POST /helper/order/basic/178/1 HTTP/1.1" 500 82823
[2017-12-05 15:59:35] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /helper/order/basic/178/1
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/helper/views.py", line 169, in order_info_first
    order = Order.objects.get(id=order_id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/query.py", line 379, in get
    self.model._meta.object_name
DoesNotExist: Order matching query does not exist.
[2017-12-05 15:59:35] ERROR [django.server.log_message:124] "POST /helper/order/basic/178/1 HTTP/1.1" 500 82823
[2017-12-05 15:59:44] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 15:59:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:47] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:47] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 15:59:48] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 15:59:48] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=3&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 15:59:48] INFO [django.server.log_message:124] "GET /helper/hospital/3/10/ HTTP/1.1" 200 6554
[2017-12-05 15:59:50] INFO [django.server.log_message:124] "POST /helper/order/basic/179/1 HTTP/1.1" 200 6445
[2017-12-05 15:59:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:00:06] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /helper/order/disease/179/
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/helper/views.py", line 288, in order_submit_first
    form = create_form(int(order.hospital.id), int(order.disease.id), appointment_form)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/dynamic_form/forms.py", line 15, in create_form
    for field in required.split():
AttributeError: 'list' object has no attribute 'split'
[2017-12-05 16:00:06] ERROR [django.server.log_message:124] "POST /helper/order/disease/179/ HTTP/1.1" 500 84497
[2017-12-05 16:00:28] INFO [django.server.log_message:124] "POST /helper/order/disease/179/ HTTP/1.1" 200 5165
[2017-12-05 16:00:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:03:15] INFO [django.server.log_message:124] "POST /helper/order/disease/179/ HTTP/1.1" 200 5165
[2017-12-05 16:03:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:08:29] INFO [django.server.log_message:124] "POST /helper/order/disease/179/ HTTP/1.1" 200 5165
[2017-12-05 16:08:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:08:58] INFO [django.server.log_message:124] "POST /helper/order/disease/179/ HTTP/1.1" 200 5165
[2017-12-05 16:08:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:13:33] INFO [django.server.log_message:124] "POST /helper/order/document/179/ HTTP/1.1" 200 3513
[2017-12-05 16:13:33] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:13:39] INFO [django.server.log_message:124] "GET /helper/order/deposit/179/?csrfmiddlewaretoken=1n9jMTq1iouDI6UBwE4t3QniF0xIFSVl0Ezdz8IvC2b5GQXQZLWUmXEsiX3M0mZK HTTP/1.1" 200 2974
[2017-12-05 16:13:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:02] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 16:14:03] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 16:14:03] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:11] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 16:14:18] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:18] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=3&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 16:14:18] INFO [django.server.log_message:124] "GET /helper/hospital/3/10/ HTTP/1.1" 200 6554
[2017-12-05 16:14:19] INFO [django.server.log_message:124] "POST /helper/order/basic/180/1 HTTP/1.1" 200 6445
[2017-12-05 16:14:19] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:30] INFO [django.server.log_message:124] "POST /helper/order/disease/180/ HTTP/1.1" 200 5165
[2017-12-05 16:14:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:14:49] INFO [django.server.log_message:124] "POST /helper/order/document/180/ HTTP/1.1" 200 3513
[2017-12-05 16:14:49] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 16:18:39] INFO [django.server.log_message:124] "POST /helper/order/disease/180/ HTTP/1.1" 200 5204
[2017-12-05 16:18:39] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:14] INFO [django.server.log_message:124] "POST /helper/order/disease/180/ HTTP/1.1" 200 5195
[2017-12-05 20:18:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:27] INFO [django.server.log_message:124] "POST /helper/order/document/180/ HTTP/1.1" 200 3715
[2017-12-05 20:18:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:30] INFO [django.server.log_message:124] "GET /helper/order/deposit/180/?csrfmiddlewaretoken=aaMqRc6mI6laasMf3aPPAvvRRiInCuSk9rckEroQ2K2C8cPuwhHgTCM1uferXYWJ HTTP/1.1" 200 2923
[2017-12-05 20:18:31] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:34] INFO [django.server.log_message:124] "POST /helper/order/deposit/180/?csrfmiddlewaretoken=aaMqRc6mI6laasMf3aPPAvvRRiInCuSk9rckEroQ2K2C8cPuwhHgTCM1uferXYWJ HTTP/1.1" 302 0
[2017-12-05 20:18:34] INFO [django.server.log_message:124] "GET /helper/order/submit/180/ HTTP/1.1" 200 2542
[2017-12-05 20:18:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:36] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4463
[2017-12-05 20:18:36] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:44] INFO [django.server.log_message:124] "GET /info/order/detail/180/ HTTP/1.1" 200 3638
[2017-12-05 20:18:44] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:50] INFO [django.server.log_message:124] "GET /info/order/detail/180/ HTTP/1.1" 200 3638
[2017-12-05 20:18:50] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:18:52] INFO [django.server.log_message:124] "GET /info/order/extradoc/180/? HTTP/1.1" 200 3616
[2017-12-05 20:18:52] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:20:55] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 20:20:55] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:20:56] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 20:20:56] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:20:58] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7913
[2017-12-05 20:20:58] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:20:59] INFO [django.server.log_message:124] "GET /helper/hospital/3/10/ HTTP/1.1" 200 6554
[2017-12-05 20:20:59] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:21:00] INFO [django.server.log_message:124] "GET /helper/hospital/bookmark/?hospital_id=3&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 20:21:01] INFO [django.server.log_message:124] "POST /helper/order/basic/181/3 HTTP/1.1" 200 6445
[2017-12-05 20:21:01] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:21:04] INFO [django.server.log_message:124] "GET /helper/order/patients/181/ HTTP/1.1" 200 3701
[2017-12-05 20:21:04] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:21:06] INFO [django.server.log_message:124] "GET /helper/order/patients/181/40/? HTTP/1.1" 200 5156
[2017-12-05 20:21:06] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:21:15] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:21:15] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4817
[2017-12-05 20:26:27] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:26:27] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4817
[2017-12-05 20:26:28] INFO [django.server.log_message:124] "GET /info/order/detail/179/ HTTP/1.1" 200 3555
[2017-12-05 20:26:28] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:26:31] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /info/order/extradoc/179/
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/info/views.py", line 216, in add_doc
    'form': create_form(int(order.hospital.id), int(order.disease.id), DocAddForm(), only_optional=True),
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/info/forms.py", line 98, in __init__
    super(DocAddForm, self).__init__(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/forms/models.py", line 280, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
[2017-12-05 20:26:31] ERROR [django.server.log_message:124] "GET /info/order/extradoc/179/? HTTP/1.1" 500 77189
[2017-12-05 20:27:25] INFO [django.server.log_message:124] "GET /info/order/detail/179/ HTTP/1.1" 200 3555
[2017-12-05 20:27:25] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:27:26] INFO [django.server.log_message:124] "GET /info/order/extradoc/179/? HTTP/1.1" 200 3219
[2017-12-05 20:27:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:27:29] INFO [django.server.log_message:124] "POST /info/order/ HTTP/1.1" 200 4817
[2017-12-05 20:27:30] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:32:29] INFO [django.server.log_message:124] "GET /info/order/extradoc/179/? HTTP/1.1" 200 3219
[2017-12-05 20:32:29] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:32:34] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /info/order/extradoc/179/
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/info/views.py", line 213, in add_doc
    return redirect('info_order', customer.id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'info_order' with arguments '(23L,)' not found. 1 pattern(s) tried: ['info/order/$']
[2017-12-05 20:32:34] ERROR [django.server.log_message:124] "POST /info/order/extradoc/179/ HTTP/1.1" 500 91704
[2017-12-05 20:33:54] INFO [django.server.log_message:124] "POST /info/order/extradoc/179/ HTTP/1.1" 302 0
[2017-12-05 20:33:54] ERROR [django.request.handle_uncaught_exception:135] Internal Server Error: /info/order/detail/23/
Traceback (most recent call last):
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jiashenc/Dropbox/website/medi_connect_site/info/views.py", line 188, in order_detail
    order = Order.objects.get(id=order_id)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jiashenc/Library/Python/2.7/lib/python/site-packages/django/db/models/query.py", line 379, in get
    self.model._meta.object_name
DoesNotExist: Order matching query does not exist.
[2017-12-05 20:33:54] ERROR [django.server.log_message:124] "GET /info/order/detail/23/ HTTP/1.1" 500 81840
[2017-12-05 20:34:09] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:34:09] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4817
[2017-12-05 20:34:11] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:34:11] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4817
[2017-12-05 20:34:13] INFO [django.server.log_message:124] "GET /info/order/detail/181/ HTTP/1.1" 200 3216
[2017-12-05 20:34:13] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:34:14] INFO [django.server.log_message:124] "GET /info/order/extradoc/181/? HTTP/1.1" 200 3219
[2017-12-05 20:34:14] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:34:32] INFO [django.server.log_message:124] "POST /info/order/extradoc/181/ HTTP/1.1" 302 0
[2017-12-05 20:34:32] INFO [django.server.log_message:124] "GET /info/order/detail/181/ HTTP/1.1" 200 3281
[2017-12-05 20:34:32] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7485
[2017-12-05 20:42:49] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:42:49] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
[2017-12-05 20:42:51] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:42:51] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 4817
[2017-12-05 20:42:54] INFO [django.server.log_message:124] "POST /result/ HTTP/1.1" 200 4261
[2017-12-05 20:42:54] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:42:57] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:42:57] INFO [django.server.log_message:124] "GET /core/disease_choice/10/ HTTP/1.1" 200 7931
[2017-12-05 20:44:12] INFO [django.server.log_message:124] "GET /placement/hospital/3/10/ HTTP/1.1" 200 6563
[2017-12-05 20:44:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:44:13] INFO [django.server.log_message:124] "GET /placement/hospital/bookmark/?hospital_id=3&disease_id=10&mark=false HTTP/1.1" 200 19
[2017-12-05 20:44:14] INFO [django.server.log_message:124] "GET /placement/hospital/bookmark/?hospital_id=3&disease_id=10&mark=true HTTP/1.1" 200 16
[2017-12-05 20:44:15] INFO [django.server.log_message:124] "GET /placement/hospital/bookmark/?hospital_id=3&disease_id=10&mark=true HTTP/1.1" 200 19
[2017-12-05 20:45:26] INFO [django.server.log_message:124] "GET /placement/order/basic/10/3/1 HTTP/1.1" 302 0
[2017-12-05 20:45:26] INFO [django.server.log_message:124] "GET /placement/order/basic/182/1 HTTP/1.1" 200 6451
[2017-12-05 20:45:26] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:45:34] INFO [django.server.log_message:124] "GET /placement/order/basic/10/1/1 HTTP/1.1" 302 0
[2017-12-05 20:45:34] INFO [django.server.log_message:124] "GET /placement/order/basic/183/1 HTTP/1.1" 200 6451
[2017-12-05 20:45:34] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:45:37] INFO [django.server.log_message:124] "GET /placement/order/basic/10/2/1 HTTP/1.1" 302 0
[2017-12-05 20:45:37] INFO [django.server.log_message:124] "GET /placement/order/basic/184/1 HTTP/1.1" 200 6451
[2017-12-05 20:45:37] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:45:59] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:45:59] INFO [django.server.log_message:124] "GET /info/order/ HTTP/1.1" 200 5484
[2017-12-05 20:46:12] INFO [django.server.log_message:124] "GET /jsreverse/ HTTP/1.1" 200 7521
[2017-12-05 20:46:12] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 3990
